### PR TITLE
pls

### PR DESCRIPTION
**Pull request by spacehash**

### CODE REVIEW

**Comment by bensonalec** [comment]
Not with that extra tab bro, you gotta shift-tab that real quick

**Comment by spacehash** [comment]
lol there was only one tab in my vscode idk why now it's 2 :/

**Comment by bensonalec** [comment]
Approved

**Comment by spacehash** [comment]
cool this was my first pull request lol

**Comment by bensonalec** [comment]
fair haha, I'm just testing out the frontend stack for some of my contract (ps Vue is way better than React imo)

**Pull request merged**
